import type { Tool } from "@/types/content";

export const MOCK_TOOLS: Tool[] = [
  {
    id: "t1",
    slug: "image-compressor",
    title: "Image Compressor",
    category: "Image",
    categorySlug: "image",
    description: "Shrink PNG and JPG files without losing visible quality.",
    accent: "primary",
    icon: "image",
    isFeatured: true,
  },
  {
    id: "t2",
    slug: "pdf-merger",
    title: "PDF Merger",
    category: "Document",
    categorySlug: "document",
    description: "Combine multiple PDFs into a single file in seconds.",
    accent: "danger",
    icon: "file-text",
    isTrending: true,
  },
  {
    id: "t3",
    slug: "word-counter",
    title: "Word Counter",
    category: "Text",
    categorySlug: "text",
    description: "Count words, characters, and reading time as you type.",
    accent: "success",
    icon: "type",
    isFeatured: true,
  },
  {
    id: "t4",
    slug: "qr-code-generator",
    title: "QR Code Generator",
    category: "Utility",
    categorySlug: "utility",
    description: "Turn any link or text into a downloadable QR code.",
    accent: "secondary",
    icon: "qr-code",
    isTrending: true,
  },
  {
    id: "t5",
    slug: "color-palette-picker",
    title: "Color Palette Picker",
    category: "Design",
    categorySlug: "design",
    description: "Extract a usable color palette from any image.",
    accent: "warning",
    icon: "palette",
    isFeatured: true,
  },
  {
    id: "t6",
    slug: "json-formatter",
    title: "JSON Formatter",
    category: "Developer",
    categorySlug: "developer",
    description: "Beautify, validate, and minify JSON instantly.",
    accent: "primary",
    icon: "braces",
    isFeatured: true,
    isTrending: true,
  },
];
