import type { Game } from "@/types/content";

export const MOCK_GAMES: Game[] = [
  {
    id: "g1",
    slug: "pixel-runner",
    title: "Pixel Runner",
    category: "Action",
    categorySlug: "action",
    accent: "danger",
    rating: 4.6,
    plays: 128400,
    difficulty: "Medium",
    tags: ["endless-runner", "retro", "single-player"],
    description:
      "Dash through a glitching pixel city, dodging obstacles and collecting shards as the speed ramps up. One hit ends the run — how far can you get?",
    isTrending: true,
  },
  {
    id: "g2",
    slug: "galaxy-shooter",
    title: "Galaxy Shooter",
    category: "Arcade",
    categorySlug: "arcade",
    accent: "secondary",
    rating: 4.8,
    plays: 96200,
    difficulty: "Medium",
    tags: ["shooter", "space", "single-player"],
    description:
      "Pilot a lone starfighter against waves of enemies and screen-filling bosses. Power-ups stack — greed is rewarded, until it isn't.",
    isNew: true,
  },
  {
    id: "g3",
    slug: "2048-classic",
    title: "2048 Classic",
    category: "Puzzle",
    categorySlug: "puzzle",
    accent: "warning",
    rating: 4.7,
    plays: 210500,
    difficulty: "Easy",
    tags: ["numbers", "logic", "single-player"],
    description:
      "Slide matching tiles together to reach 2048. Simple rules, an addictive curve, and a best-score counter that will not let you stop.",
    isTrending: true,
  },
  {
    id: "g4",
    slug: "car-racing-pro",
    title: "Car Racing Pro",
    category: "Racing",
    categorySlug: "racing",
    accent: "primary",
    rating: 4.5,
    plays: 74300,
    difficulty: "Medium",
    tags: ["racing", "cars", "time-trial"],
    description:
      "Drift through six tracks against the clock or a full grid of AI racers. Tune your car's grip and top speed before every race.",
  },
  {
    id: "g5",
    slug: "basketball-stars",
    title: "Basketball Stars",
    category: "Sports",
    categorySlug: "sports",
    accent: "success",
    rating: 4.4,
    plays: 58900,
    difficulty: "Easy",
    tags: ["basketball", "arcade-sports", "1v1"],
    description:
      "Quick 1-on-1 basketball with arcade physics and trick shots. Best of three, loser walks — bragging rights only.",
    isNew: true,
  },
  {
    id: "g6",
    slug: "sudoku-master",
    title: "Sudoku Master",
    category: "Puzzle",
    categorySlug: "puzzle",
    accent: "warning",
    rating: 4.6,
    plays: 43100,
    difficulty: "Hard",
    tags: ["numbers", "logic", "daily-puzzle"],
    description:
      "Four difficulty tiers from warm-up to brutal, plus a new daily puzzle every morning with a shared leaderboard.",
    isTrending: true,
  },
  {
    id: "g7",
    slug: "ninja-strike",
    title: "Ninja Strike",
    category: "Action",
    categorySlug: "action",
    accent: "danger",
    rating: 4.5,
    plays: 61700,
    difficulty: "Hard",
    tags: ["platformer", "combat", "single-player"],
    description:
      "Chain wall-jumps and precision strikes across 20 hand-built levels. One mistake usually means starting the level over.",
  },
  {
    id: "g8",
    slug: "block-puzzle-blast",
    title: "Block Puzzle Blast",
    category: "Puzzle",
    categorySlug: "puzzle",
    accent: "warning",
    rating: 4.3,
    plays: 38200,
    difficulty: "Easy",
    tags: ["blocks", "casual", "single-player"],
    description:
      "Fit falling blocks into a shrinking grid. No timer, no pressure — just a clean, satisfying loop for a five-minute break.",
  },
  {
    id: "g9",
    slug: "moto-x-extreme",
    title: "Moto X Extreme",
    category: "Racing",
    categorySlug: "racing",
    accent: "primary",
    rating: 4.2,
    plays: 29500,
    difficulty: "Hard",
    tags: ["motorbike", "stunts", "physics"],
    description:
      "Physics-based motocross across brutal hill courses. Land your flips clean or restart from the last checkpoint.",
  },
  {
    id: "g10",
    slug: "penalty-shootout",
    title: "Penalty Shootout",
    category: "Sports",
    categorySlug: "sports",
    accent: "success",
    rating: 4.1,
    plays: 33800,
    difficulty: "Easy",
    tags: ["football", "penalties", "quick-play"],
    description:
      "Best-of-five penalty shootouts. Aim with the mouse, read the keeper, and settle the score in under two minutes.",
  },
  {
    id: "g11",
    slug: "chess-arena",
    title: "Chess Arena",
    category: "Strategy",
    categorySlug: "strategy",
    accent: "secondary",
    rating: 4.7,
    plays: 51200,
    difficulty: "Hard",
    tags: ["chess", "board-game", "vs-ai"],
    description:
      "Play against an adjustable-strength AI or pass-and-play locally. Full move history and takeback support included.",
    isTrending: true,
  },
  {
    id: "g12",
    slug: "tower-defense-kingdom",
    title: "Tower Defense Kingdom",
    category: "Strategy",
    categorySlug: "strategy",
    accent: "secondary",
    rating: 4.4,
    plays: 27600,
    difficulty: "Medium",
    tags: ["tower-defense", "strategy", "waves"],
    description:
      "Place and upgrade towers across 15 waves of increasingly nasty enemy types. Every path choice matters.",
  },
];
