// scripts/seed-data.ts
// Full-shape sample records — run `npm run seed` (see scripts/seed.ts) to
// push these into Firestore so every page has real data to render on day one.
// Replace/add to these before your first deploy.

import type { Game, Tool, Post, Category, Tag } from "../lib/types";

const now = new Date().toISOString();

export const categories: Omit<Category, "id">[] = [
  { name: "Adventure", slug: "adventure", type: "game" },
  { name: "Racing", slug: "racing", type: "game" },
  { name: "Puzzle", slug: "puzzle", type: "game" },
  { name: "Action", slug: "action", type: "game" },
  { name: "Image", slug: "image", type: "tool" },
  { name: "Generator", slug: "generator", type: "tool" },
  { name: "Security", slug: "security", type: "tool" },
  { name: "Text", slug: "text", type: "tool" },
  { name: "AI", slug: "ai", type: "post" },
  { name: "SEO", slug: "seo", type: "post" },
  { name: "Productivity", slug: "productivity", type: "post" },
];

export const tags: Omit<Tag, "id">[] = [
  { name: "Free", slug: "free" },
  { name: "Browser", slug: "browser" },
  { name: "Beginner Friendly", slug: "beginner-friendly" },
  { name: "2026", slug: "2026" },
];

export const games: Omit<Game, "id">[] = [
  {
    title: "Space Adventure",
    slug: "space-adventure",
    description: "Pilot a starfighter through asteroid fields and alien ambushes.",
    thumbnail: "space",
    categoryId: "adventure",
    tagIds: ["free", "browser"],
    status: "published",
    createdAt: now,
    updatedAt: now,
    publishedAt: "2026-05-01",
    gameUrl: "https://example.com/embed/space-adventure",
    screenshots: [],
    instructions: "Survive as long as you can while collecting stars and avoiding asteroids.",
    controls: "Arrow keys to move, Space to fire.",
    developer: "Sinthia Studio",
    playCount: 18420,
    seoTitle: "Space Adventure — Free Browser Game | Sinthia",
    metaDescription: "Play Space Adventure free in your browser, no download required.",
  },
  {
    title: "Racing Extreme",
    slug: "racing-extreme",
    description: "High-speed street racing with drift mechanics and nitro boosts.",
    thumbnail: "racing",
    categoryId: "racing",
    tagIds: ["free", "browser"],
    status: "published",
    createdAt: now,
    updatedAt: now,
    publishedAt: "2026-04-22",
    gameUrl: "https://example.com/embed/racing-extreme",
    screenshots: [],
    instructions: "Race against the clock across five tracks. Drift through corners for a nitro boost.",
    controls: "W/A/S/D or Arrow keys, Shift for nitro.",
    developer: "Sinthia Studio",
    playCount: 24110,
    seoTitle: "Racing Extreme — Free Browser Racing Game | Sinthia",
    metaDescription: "Drift, boost, and race free in Racing Extreme — no install needed.",
  },
  {
    title: "Puzzle Master",
    slug: "puzzle-master",
    description: "Stack, match, and clear blocks across 100 increasingly tricky levels.",
    thumbnail: "puzzle",
    categoryId: "puzzle",
    tagIds: ["free", "browser", "beginner-friendly"],
    status: "published",
    createdAt: now,
    updatedAt: now,
    publishedAt: "2026-03-14",
    gameUrl: "https://example.com/embed/puzzle-master",
    screenshots: [],
    instructions: "Clear rows by matching three or more blocks of the same color before time runs out.",
    controls: "Mouse or touch to select and swap blocks.",
    developer: "Sinthia Studio",
    playCount: 31980,
    seoTitle: "Puzzle Master — Free Match-3 Puzzle Game | Sinthia",
    metaDescription: "100 levels of match-3 puzzle fun, free and instant in your browser.",
  },
  {
    title: "Zombie Survival",
    slug: "zombie-survival",
    description: "Fortify, scavenge, and hold the line against endless zombie waves.",
    thumbnail: "zombie",
    categoryId: "action",
    tagIds: ["free", "browser"],
    status: "published",
    createdAt: now,
    updatedAt: now,
    publishedAt: "2026-06-02",
    gameUrl: "https://example.com/embed/zombie-survival",
    screenshots: [],
    instructions: "Build barricades between waves and manage ammo carefully — headshots save bullets.",
    controls: "WASD to move, Mouse to aim/shoot, R to reload.",
    developer: "Sinthia Studio",
    playCount: 15230,
    seoTitle: "Zombie Survival — Free Browser Survival Game | Sinthia",
    metaDescription: "Hold the line against zombie hordes, free to play in your browser.",
  },
];

export const tools: Omit<Tool, "id">[] = [
  {
    title: "Image Compressor",
    slug: "image-compressor",
    description: "Shrink JPG, PNG, and WebP files without losing visible quality.",
    thumbnail: "",
    categoryId: "image",
    tagIds: ["free", "browser"],
    status: "published",
    createdAt: now,
    updatedAt: now,
    publishedAt: "2026-02-10",
    toolUrl: "/tools/image-compressor",
    instructions: "Upload an image, choose a compression level, and download the optimized file.",
    usageCount: 52310,
    faq: [
      { question: "Is my image uploaded to a server?", answer: "No — compression runs locally in your browser." },
      { question: "What formats are supported?", answer: "JPG, PNG, and WebP." },
    ],
    seoTitle: "Free Image Compressor Online | Sinthia",
    metaDescription: "Compress JPG, PNG, and WebP images online for free, no upload required.",
  },
  {
    title: "QR Code Generator",
    slug: "qr-code-generator",
    description: "Turn any link, text, or contact card into a downloadable QR code.",
    thumbnail: "",
    categoryId: "generator",
    tagIds: ["free", "browser"],
    status: "published",
    createdAt: now,
    updatedAt: now,
    publishedAt: "2026-01-28",
    toolUrl: "/tools/qr-code-generator",
    instructions: "Enter a URL or text, customize the color, and download as PNG or SVG.",
    usageCount: 41870,
    faq: [{ question: "Do the QR codes expire?", answer: "No, they're static and work forever." }],
    seoTitle: "Free QR Code Generator | Sinthia",
    metaDescription: "Generate free QR codes for links, text, or contact info, downloadable instantly.",
  },
  {
    title: "Password Generator",
    slug: "password-generator",
    description: "Create strong, random passwords with custom length and character rules.",
    thumbnail: "",
    categoryId: "security",
    tagIds: ["free", "browser"],
    status: "published",
    createdAt: now,
    updatedAt: now,
    publishedAt: "2026-01-15",
    toolUrl: "/tools/password-generator",
    instructions: "Set your desired length and character types, then generate and copy.",
    usageCount: 68940,
    faq: [{ question: "Are generated passwords stored anywhere?", answer: "No, everything happens in your browser." }],
    seoTitle: "Free Strong Password Generator | Sinthia",
    metaDescription: "Generate strong, random passwords for free — fully client-side, nothing stored.",
  },
  {
    title: "Text Counter",
    slug: "text-counter",
    description: "Count words, characters, sentences, and reading time as you type.",
    thumbnail: "",
    categoryId: "text",
    tagIds: ["free", "browser", "beginner-friendly"],
    status: "published",
    createdAt: now,
    updatedAt: now,
    publishedAt: "2026-01-05",
    toolUrl: "/tools/text-counter",
    instructions: "Paste or type your text to see live word, character, and reading-time counts.",
    usageCount: 37650,
    seoTitle: "Free Word & Character Counter | Sinthia",
    metaDescription: "Count words, characters, and reading time instantly, free and online.",
  },
];

export const posts: Omit<Post, "id">[] = [
  {
    title: "10 Amazing AI Tools You Should Try in 2026",
    slug: "ai-tools-2026",
    description: "A roundup of AI tools that actually save you time this year.",
    thumbnail: "",
    categoryId: "ai",
    tagIds: ["2026"],
    status: "published",
    createdAt: now,
    updatedAt: now,
    publishedAt: "2026-07-10",
    content:
      "AI tooling has matured fast this year. Here are ten tools worth bookmarking, spanning writing, image generation, coding assistants, and research — with notes on what each is actually good for and where it falls short.",
    excerpt: "A roundup of AI tools that actually save you time in 2026.",
    featuredImage: "",
    authorId: "Admin",
    faq: [
      { question: "Are these tools free?", answer: "Most have a usable free tier; a few are paid-only." },
    ],
    seoTitle: "10 Amazing AI Tools You Should Try in 2026 | Sinthia Blog",
    metaDescription: "Ten AI tools worth trying in 2026, with honest notes on strengths and limits.",
  },
  {
    title: "The Future of Web Gaming: Trends to Watch",
    slug: "future-web-gaming",
    description: "WebGPU, cloud play, and what's next for browser-based games.",
    thumbnail: "",
    categoryId: "ai",
    tagIds: ["2026"],
    status: "published",
    createdAt: now,
    updatedAt: now,
    publishedAt: "2026-07-08",
    content:
      "Browser games are catching up to native performance thanks to WebGPU and better engines. This piece looks at where the technology is headed and what it means for players and indie developers alike.",
    excerpt: "WebGPU, cloud play, and what's next for browser-based games.",
    featuredImage: "",
    authorId: "John Doe",
    seoTitle: "The Future of Web Gaming: Trends to Watch | Sinthia Blog",
    metaDescription: "A look at where browser gaming technology is headed in 2026 and beyond.",
  },
  {
    title: "How to Stay Productive with Online Tools",
    slug: "productive-online-tools",
    description: "Small, free tools that remove everyday friction from your workflow.",
    thumbnail: "",
    categoryId: "productivity",
    tagIds: ["free"],
    status: "published",
    createdAt: now,
    updatedAt: now,
    publishedAt: "2026-07-05",
    content:
      "You don't need a subscription stack to be productive. This guide walks through lightweight, free browser tools — from text counters to QR generators — and how to build them into a faster daily workflow.",
    excerpt: "Small, free tools that remove everyday friction from your workflow.",
    featuredImage: "",
    authorId: "Sarah Smith",
    seoTitle: "How to Stay Productive with Online Tools | Sinthia Blog",
    metaDescription: "Free browser tools that quietly remove friction from your daily workflow.",
  },
  {
    title: "SEO Best Practices for Bloggers in 2026",
    slug: "seo-best-practices",
    description: "The fundamentals that still matter, and what's changed this year.",
    thumbnail: "",
    categoryId: "seo",
    tagIds: ["2026"],
    status: "published",
    createdAt: now,
    updatedAt: now,
    publishedAt: "2026-07-02",
    content:
      "Search fundamentals haven't changed as much as the headlines suggest — but AI-generated results have shifted how visibility works. Here's what still matters and what's genuinely new for bloggers in 2026.",
    excerpt: "The SEO fundamentals that still matter, and what's genuinely new in 2026.",
    featuredImage: "",
    authorId: "Admin",
    seoTitle: "SEO Best Practices for Bloggers in 2026 | Sinthia Blog",
    metaDescription: "What still matters for blog SEO in 2026, and what's genuinely changed.",
  },
];
